package ge.vazisu.gaudium.enums;

import lombok.Getter;

import java.util.stream.Stream;

/**
 * Criteria.
 *
 * @author Pavel_Datunashvili
 */
@Getter
public enum Criteria {

    /**
     * Статистика турнира из базы данных FON
     */
    DB_TOURNAMENT_0(0, "База данных. Турнир. WDL. Приемущество 1"),
    DB_TOURNAMENT_1(0, "База данных. Турнир. WDL. Приемущество Х"),
    DB_TOURNAMENT_2(0, "База данных. Турнир. WDL. Приемущество 2"),
    DB_TOURNAMENT_3(0, "База данных. Турнир. WDL. Приемущество 1Х"),
    DB_TOURNAMENT_4(0, "База данных. Турнир. WDL. Приемущество 12"),
    DB_TOURNAMENT_5(0, "База данных. Турнир. WDL. Приемущество Х2"),
    DB_TOURNAMENT_6(0, "База данных. Турнир. WDL. Серия 1"),
    DB_TOURNAMENT_7(0, "База данных. Турнир. WDL. Серия Х"),
    DB_TOURNAMENT_8(0, "База данных. Турнир. WDL. Серия 2"),
    DB_TOURNAMENT_9(0, "База данных. Турнир. WDL. Серия без 1"),
    DB_TOURNAMENT_10(0, "База данных. Турнир. WDL. Серия без Х"),
    DB_TOURNAMENT_11(0, "База данных. Турнир. WDL. Серия без 2"),
    DB_TOURNAMENT_12(0, "База данных. Турнир. FON. Приемущество 1"),
    DB_TOURNAMENT_13(0, "База данных. Турнир. FON. Приемущество Х"),
    DB_TOURNAMENT_14(0, "База данных. Турнир. FON. Приемущество 2"),
    DB_TOURNAMENT_15(0, "База данных. Турнир. FON. Приемущество 1Х"),
    DB_TOURNAMENT_16(0, "База данных. Турнир. FON. Приемущество 12"),
    DB_TOURNAMENT_17(0, "База данных. Турнир. FON. Приемущество Х2"),
    DB_TOURNAMENT_18(0, "База данных. Турнир. FON. Серия 1"),
    DB_TOURNAMENT_19(0, "База данных. Турнир. FON. Серия Х"),
    DB_TOURNAMENT_20(0, "База данных. Турнир. FON. Серия 2"),
    DB_TOURNAMENT_21(0, "База данных. Турнир. FON. Серия без 1"),
    DB_TOURNAMENT_22(0, "База данных. Турнир. FON. Серия без Х"),
    DB_TOURNAMENT_23(0, "База данных. Турнир. FON. Серия без 2"),
    DB_TOURNAMENT_24(0, "База данных. Турнир. MAN. Приемущество 1"),
    DB_TOURNAMENT_25(0, "База данных. Турнир. MAN. Приемущество Х"),
    DB_TOURNAMENT_26(0, "База данных. Турнир. MAN. Приемущество 2"),
    DB_TOURNAMENT_27(0, "База данных. Турнир. MAN. Приемущество 1Х"),
    DB_TOURNAMENT_28(0, "База данных. Турнир. MAN. Приемущество 12"),
    DB_TOURNAMENT_29(0, "База данных. Турнир. MAN. Приемущество Х2"),
    DB_TOURNAMENT_30(0, "База данных. Турнир. MAN. Серия 1"),
    DB_TOURNAMENT_31(0, "База данных. Турнир. MAN. Серия Х"),
    DB_TOURNAMENT_32(0, "База данных. Турнир. MAN. Серия 2"),
    DB_TOURNAMENT_33(0, "База данных. Турнир. MAN. Серия без 1"),
    DB_TOURNAMENT_34(0, "База данных. Турнир. MAN. Серия без Х"),
    DB_TOURNAMENT_35(0, "База данных. Турнир. MAN. Серия без 2"),



    DB_HOME_0(1, "База данных. Хозяева. WDL. Приемущество 1"),
    DB_HOME_1(1, "База данных. Хозяева. WDL. Приемущество Х"),
    DB_HOME_2(1, "База данных. Хозяева. WDL. Приемущество 2"),
    DB_HOME_3(1, "База данных. Хозяева. WDL. Приемущество 1Х"),
    DB_HOME_4(1, "База данных. Хозяева. WDL. Приемущество 12"),
    DB_HOME_5(1, "База данных. Хозяева. WDL. Приемущество Х2"),
    DB_HOME_6(1, "База данных. Хозяева. WDL. Серия 1"),
    DB_HOME_7(1, "База данных. Хозяева. WDL. Серия Х"),
    DB_HOME_8(1, "База данных. Хозяева. WDL. Серия 2"),
    DB_HOME_9(1, "База данных. Хозяева. WDL. Серия без 1"),
    DB_HOME_10(1, "База данных. Хозяева. WDL. Серия без Х"),
    DB_HOME_11(1, "База данных. Хозяева. WDL. Серия без 2"),
    DB_HOME_12(1, "База данных. Хозяева. FON. Приемущество 1"),
    DB_HOME_13(1, "База данных. Хозяева. FON. Приемущество Х"),
    DB_HOME_14(1, "База данных. Хозяева. FON. Приемущество 2"),
    DB_HOME_15(1, "База данных. Хозяева. FON. Приемущество 1Х"),
    DB_HOME_16(1, "База данных. Хозяева. FON. Приемущество 12"),
    DB_HOME_17(1, "База данных. Хозяева. FON. Приемущество Х2"),
    DB_HOME_18(1, "База данных. Хозяева. FON. Серия 1"),
    DB_HOME_19(1, "База данных. Хозяева. FON. Серия Х"),
    DB_HOME_20(1, "База данных. Хозяева. FON. Серия 2"),
    DB_HOME_21(1, "База данных. Хозяева. FON. Серия без 1"),
    DB_HOME_22(1, "База данных. Хозяева. FON. Серия без Х"),
    DB_HOME_23(1, "База данных. Хозяева. FON. Серия без 2"),
    DB_HOME_24(1, "База данных. Хозяева. MAN. Приемущество 1"),
    DB_HOME_25(1, "База данных. Хозяева. MAN. Приемущество Х"),
    DB_HOME_26(1, "База данных. Хозяева. MAN. Приемущество 2"),
    DB_HOME_27(1, "База данных. Хозяева. MAN. Приемущество 1Х"),
    DB_HOME_28(1, "База данных. Хозяева. MAN. Приемущество 12"),
    DB_HOME_29(1, "База данных. Хозяева. MAN. Приемущество Х2"),
    DB_HOME_30(1, "База данных. Хозяева. MAN. Серия 1"),
    DB_HOME_31(1, "База данных. Хозяева. MAN. Серия Х"),
    DB_HOME_32(1, "База данных. Хозяева. MAN. Серия 2"),
    DB_HOME_33(1, "База данных. Хозяева. MAN. Серия без 1"),
    DB_HOME_34(1, "База данных. Хозяева. MAN. Серия без Х"),
    DB_HOME_35(1, "База данных. Хозяева. MAN. Серия без 2"),




    DB_AWAY_0(2, "База данных. Гости. WDL. Приемущество 1"),
    DB_AWAY_1(2, "База данных. Гости. WDL. Приемущество Х"),
    DB_AWAY_2(2, "База данных. Гости. WDL. Приемущество 2"),
    DB_AWAY_3(2, "База данных. Гости. WDL. Приемущество 1Х"),
    DB_AWAY_4(2, "База данных. Гости. WDL. Приемущество 12"),
    DB_AWAY_5(2, "База данных. Гости. WDL. Приемущество Х2"),
    DB_AWAY_6(2, "База данных. Гости. WDL. Серия 1"),
    DB_AWAY_7(2, "База данных. Гости. WDL. Серия Х"),
    DB_AWAY_8(2, "База данных. Гости. WDL. Серия 2"),
    DB_AWAY_9(2, "База данных. Гости. WDL. Серия без 1"),
    DB_AWAY_10(2, "База данных. Гости. WDL. Серия без Х"),
    DB_AWAY_11(2, "База данных. Гости. WDL. Серия без 2"),
    DB_AWAY_12(2, "База данных. Гости. FON. Приемущество 1"),
    DB_AWAY_13(2, "База данных. Гости. FON. Приемущество Х"),
    DB_AWAY_14(2, "База данных. Гости. FON. Приемущество 2"),
    DB_AWAY_15(2, "База данных. Гости. FON. Приемущество 1Х"),
    DB_AWAY_16(2, "База данных. Гости. FON. Приемущество 12"),
    DB_AWAY_17(2, "База данных. Гости. FON. Приемущество Х2"),
    DB_AWAY_18(2, "База данных. Гости. FON. Серия 1"),
    DB_AWAY_19(2, "База данных. Гости. FON. Серия Х"),
    DB_AWAY_20(2, "База данных. Гости. FON. Серия 2"),
    DB_AWAY_21(2, "База данных. Гости. FON. Серия без 1"),
    DB_AWAY_22(2, "База данных. Гости. FON. Серия без Х"),
    DB_AWAY_23(2, "База данных. Гости. FON. Серия без 2"),
    DB_AWAY_24(2, "База данных. Гости. MAN. Приемущество 1"),
    DB_AWAY_25(2, "База данных. Гости. MAN. Приемущество Х"),
    DB_AWAY_26(2, "База данных. Гости. MAN. Приемущество 2"),
    DB_AWAY_27(2, "База данных. Гости. MAN. Приемущество 1Х"),
    DB_AWAY_28(2, "База данных. Гости. MAN. Приемущество 12"),
    DB_AWAY_29(2, "База данных. Гости. MAN. Приемущество Х2"),
    DB_AWAY_30(2, "База данных. Гости. MAN. Серия 1"),
    DB_AWAY_31(2, "База данных. Гости. MAN. Серия Х"),
    DB_AWAY_32(2, "База данных. Гости. MAN. Серия 2"),
    DB_AWAY_33(2, "База данных. Гости. MAN. Серия без 1"),
    DB_AWAY_34(2, "База данных. Гости. MAN. Серия без Х"),
    DB_AWAY_35(2, "База данных. Гости. MAN. Серия без 2"),


    DB_HOME_ONLY_0(3, "База данных. Хозяева дома. WDL. Приемущество 1"),
    DB_HOME_ONLY_1(3, "База данных. Хозяева дома. WDL. Приемущество Х"),
    DB_HOME_ONLY_2(3, "База данных. Хозяева дома. WDL. Приемущество 2"),
    DB_HOME_ONLY_3(3, "База данных. Хозяева дома. WDL. Приемущество 1Х"),
    DB_HOME_ONLY_4(3, "База данных. Хозяева дома. WDL. Приемущество 12"),
    DB_HOME_ONLY_5(3, "База данных. Хозяева дома. WDL. Приемущество Х2"),
    DB_HOME_ONLY_6(3, "База данных. Хозяева дома. WDL. Серия 1"),
    DB_HOME_ONLY_7(3, "База данных. Хозяева дома. WDL. Серия Х"),
    DB_HOME_ONLY_8(3, "База данных. Хозяева дома. WDL. Серия 2"),
    DB_HOME_ONLY_9(3, "База данных. Хозяева дома. WDL. Серия без 1"),
    DB_HOME_ONLY_10(3, "База данных. Хозяева дома. WDL. Серия без Х"),
    DB_HOME_ONLY_11(3, "База данных. Хозяева дома. WDL. Серия без 2"),
    DB_HOME_ONLY_12(3, "База данных. Хозяева дома. FON. Приемущество 1"),
    DB_HOME_ONLY_13(3, "База данных. Хозяева дома. FON. Приемущество Х"),
    DB_HOME_ONLY_14(3, "База данных. Хозяева дома. FON. Приемущество 2"),
    DB_HOME_ONLY_15(3, "База данных. Хозяева дома. FON. Приемущество 1Х"),
    DB_HOME_ONLY_16(3, "База данных. Хозяева дома. FON. Приемущество 12"),
    DB_HOME_ONLY_17(3, "База данных. Хозяева дома. FON. Приемущество Х2"),
    DB_HOME_ONLY_18(3, "База данных. Хозяева дома. FON. Серия 1"),
    DB_HOME_ONLY_19(3, "База данных. Хозяева дома. FON. Серия Х"),
    DB_HOME_ONLY_20(3, "База данных. Хозяева дома. FON. Серия 2"),
    DB_HOME_ONLY_21(3, "База данных. Хозяева дома. FON. Серия без 1"),
    DB_HOME_ONLY_22(3, "База данных. Хозяева дома. FON. Серия без Х"),
    DB_HOME_ONLY_23(3, "База данных. Хозяева дома. FON. Серия без 2"),
    DB_HOME_ONLY_24(3, "База данных. Хозяева дома. MAN. Приемущество 1"),
    DB_HOME_ONLY_25(3, "База данных. Хозяева дома. MAN. Приемущество Х"),
    DB_HOME_ONLY_26(3, "База данных. Хозяева дома. MAN. Приемущество 2"),
    DB_HOME_ONLY_27(3, "База данных. Хозяева дома. MAN. Приемущество 1Х"),
    DB_HOME_ONLY_28(3, "База данных. Хозяева дома. MAN. Приемущество 12"),
    DB_HOME_ONLY_29(3, "База данных. Хозяева дома. MAN. Приемущество Х2"),
    DB_HOME_ONLY_30(3, "База данных. Хозяева дома. MAN. Серия 1"),
    DB_HOME_ONLY_31(3, "База данных. Хозяева дома. MAN. Серия Х"),
    DB_HOME_ONLY_32(3, "База данных. Хозяева дома. MAN. Серия 2"),
    DB_HOME_ONLY_33(3, "База данных. Хозяева дома. MAN. Серия без 1"),
    DB_HOME_ONLY_34(3, "База данных. Хозяева дома. MAN. Серия без Х"),
    DB_HOME_ONLY_35(3, "База данных. Хозяева дома. MAN. Серия без 2"),

    DB_AWAY_ONLY_0(4, "База данных. Гости в гостях. WDL. Приемущество 1"),
    DB_AWAY_ONLY_1(4, "База данных. Гости в гостях. WDL. Приемущество Х"),
    DB_AWAY_ONLY_2(4, "База данных. Гости в гостях. WDL. Приемущество 2"),
    DB_AWAY_ONLY_3(4, "База данных. Гости в гостях. WDL. Приемущество 1Х"),
    DB_AWAY_ONLY_4(4, "База данных. Гости в гостях. WDL. Приемущество 12"),
    DB_AWAY_ONLY_5(4, "База данных. Гости в гостях. WDL. Приемущество Х2"),
    DB_AWAY_ONLY_6(4, "База данных. Гости в гостях. WDL. Серия 1"),
    DB_AWAY_ONLY_7(4, "База данных. Гости в гостях. WDL. Серия Х"),
    DB_AWAY_ONLY_8(4, "База данных. Гости в гостях. WDL. Серия 2"),
    DB_AWAY_ONLY_9(4, "База данных. Гости в гостях. WDL. Серия без 1"),
    DB_AWAY_ONLY_10(4, "База данных. Гости в гостях. WDL. Серия без Х"),
    DB_AWAY_ONLY_11(4, "База данных. Гости в гостях. WDL. Серия без 2"),
    DB_AWAY_ONLY_12(4, "База данных. Гости в гостях. FON. Приемущество 1"),
    DB_AWAY_ONLY_13(4, "База данных. Гости в гостях. FON. Приемущество Х"),
    DB_AWAY_ONLY_14(4, "База данных. Гости в гостях. FON. Приемущество 2"),
    DB_AWAY_ONLY_15(4, "База данных. Гости в гостях. FON. Приемущество 1Х"),
    DB_AWAY_ONLY_16(4, "База данных. Гости в гостях. FON. Приемущество 12"),
    DB_AWAY_ONLY_17(4, "База данных. Гости в гостях. FON. Приемущество Х2"),
    DB_AWAY_ONLY_18(4, "База данных. Гости в гостях. FON. Серия 1"),
    DB_AWAY_ONLY_19(4, "База данных. Гости в гостях. FON. Серия Х"),
    DB_AWAY_ONLY_20(4, "База данных. Гости в гостях. FON. Серия 2"),
    DB_AWAY_ONLY_21(4, "База данных. Гости в гостях. FON. Серия без 1"),
    DB_AWAY_ONLY_22(4, "База данных. Гости в гостях. FON. Серия без Х"),
    DB_AWAY_ONLY_23(4, "База данных. Гости в гостях. FON. Серия без 2"),
    DB_AWAY_ONLY_24(4, "База данных. Гости в гостях. MAN. Приемущество 1"),
    DB_AWAY_ONLY_25(4, "База данных. Гости в гостях. MAN. Приемущество Х"),
    DB_AWAY_ONLY_26(4, "База данных. Гости в гостях. MAN. Приемущество 2"),
    DB_AWAY_ONLY_27(4, "База данных. Гости в гостях. MAN. Приемущество 1Х"),
    DB_AWAY_ONLY_28(4, "База данных. Гости в гостях. MAN. Приемущество 12"),
    DB_AWAY_ONLY_29(4, "База данных. Гости в гостях. MAN. Приемущество Х2"),
    DB_AWAY_ONLY_30(4, "База данных. Гости в гостях. MAN. Серия 1"),
    DB_AWAY_ONLY_31(4, "База данных. Гости в гостях. MAN. Серия Х"),
    DB_AWAY_ONLY_32(4, "База данных. Гости в гостях. MAN. Серия 2"),
    DB_AWAY_ONLY_33(4, "База данных. Гости в гостях. MAN. Серия без 1"),
    DB_AWAY_ONLY_34(4, "База данных. Гости в гостях. MAN. Серия без Х"),
    DB_AWAY_ONLY_35(4, "База данных. Гости в гостях. MAN. Серия без 2"),


    DB_H2H_0(5, "База данных. H2H. WDL. Приемущество 1"),
    DB_H2H_1(5, "База данных. H2H. WDL. Приемущество Х"),
    DB_H2H_2(5, "База данных. H2H. WDL. Приемущество 2"),
    DB_H2H_3(5, "База данных. H2H. WDL. Приемущество 1Х"),
    DB_H2H_4(5, "База данных. H2H. WDL. Приемущество 12"),
    DB_H2H_5(5, "База данных. H2H. WDL. Приемущество Х2"),
    DB_H2H_6(5, "База данных. H2H. WDL. Серия 1"),
    DB_H2H_7(5, "База данных. H2H. WDL. Серия Х"),
    DB_H2H_8(5, "База данных. H2H. WDL. Серия 2"),
    DB_H2H_9(5, "База данных. H2H. WDL. Серия без 1"),
    DB_H2H_10(5, "База данных. H2H. WDL. Серия без Х"),
    DB_H2H_11(5, "База данных. H2H. WDL. Серия без 2"),
    DB_H2H_12(5, "База данных. H2H. FON. Приемущество 1"),
    DB_H2H_13(5, "База данных. H2H. FON. Приемущество Х"),
    DB_H2H_14(5, "База данных. H2H. FON. Приемущество 2"),
    DB_H2H_15(5, "База данных. H2H. FON. Приемущество 1Х"),
    DB_H2H_16(5, "База данных. H2H. FON. Приемущество 12"),
    DB_H2H_17(5, "База данных. H2H. FON. Приемущество Х2"),
    DB_H2H_18(5, "База данных. H2H. FON. Серия 1"),
    DB_H2H_19(5, "База данных. H2H. FON. Серия Х"),
    DB_H2H_20(5, "База данных. H2H. FON. Серия 2"),
    DB_H2H_21(5, "База данных. H2H. FON. Серия без 1"),
    DB_H2H_22(5, "База данных. H2H. FON. Серия без Х"),
    DB_H2H_23(5, "База данных. H2H. FON. Серия без 2"),
    DB_H2H_24(5, "База данных. H2H. MAN. Приемущество 1"),
    DB_H2H_25(5, "База данных. H2H. MAN. Приемущество Х"),
    DB_H2H_26(5, "База данных. H2H. MAN. Приемущество 2"),
    DB_H2H_27(5, "База данных. H2H. MAN. Приемущество 1Х"),
    DB_H2H_28(5, "База данных. H2H. MAN. Приемущество 12"),
    DB_H2H_29(5, "База данных. H2H. MAN. Приемущество Х2"),
    DB_H2H_30(5, "База данных. H2H. MAN. Серия 1"),
    DB_H2H_31(5, "База данных. H2H. MAN. Серия Х"),
    DB_H2H_32(5, "База данных. H2H. MAN. Серия 2"),
    DB_H2H_33(5, "База данных. H2H. MAN. Серия без 1"),
    DB_H2H_34(5, "База данных. H2H. MAN. Серия без Х"),
    DB_H2H_35(5, "База данных. H2H. MAN. Серия без 2"),

    DB_FON_VALUES_0(6, "База данных. FON. WDL. Приемущество 1"),
    DB_FON_VALUES_1(6, "База данных. FON. WDL. Приемущество Х"),
    DB_FON_VALUES_2(6, "База данных. FON. WDL. Приемущество 2"),
    DB_FON_VALUES_3(6, "База данных. FON. WDL. Приемущество 1Х"),
    DB_FON_VALUES_4(6, "База данных. FON. WDL. Приемущество 12"),
    DB_FON_VALUES_5(6, "База данных. FON. WDL. Приемущество Х2"),
    DB_FON_VALUES_6(6, "База данных. FON. WDL. Серия 1"),
    DB_FON_VALUES_7(6, "База данных. FON. WDL. Серия Х"),
    DB_FON_VALUES_8(6, "База данных. FON. WDL. Серия 2"),
    DB_FON_VALUES_9(6, "База данных. FON. WDL. Серия без 1"),
    DB_FON_VALUES_10(6, "База данных. FON. WDL. Серия без Х"),
    DB_FON_VALUES_11(6, "База данных. FON. WDL. Серия без 2"),
    DB_FON_VALUES_12(6, "База данных. FON. FON. Приемущество 1"),
    DB_FON_VALUES_13(6, "База данных. FON. FON. Приемущество Х"),
    DB_FON_VALUES_14(6, "База данных. FON. FON. Приемущество 2"),
    DB_FON_VALUES_15(6, "База данных. FON. FON. Приемущество 1Х"),
    DB_FON_VALUES_16(6, "База данных. FON. FON. Приемущество 12"),
    DB_FON_VALUES_17(6, "База данных. FON. FON. Приемущество Х2"),
    DB_FON_VALUES_18(6, "База данных. FON. FON. Серия 1"),
    DB_FON_VALUES_19(6, "База данных. FON. FON. Серия Х"),
    DB_FON_VALUES_20(6, "База данных. FON. FON. Серия 2"),
    DB_FON_VALUES_21(6, "База данных. FON. FON. Серия без 1"),
    DB_FON_VALUES_22(6, "База данных. FON. FON. Серия без Х"),
    DB_FON_VALUES_23(6, "База данных. FON. FON. Серия без 2"),
    DB_FON_VALUES_24(6, "База данных. FON. MAN. Приемущество 1"),
    DB_FON_VALUES_25(6, "База данных. FON. MAN. Приемущество Х"),
    DB_FON_VALUES_26(6, "База данных. FON. MAN. Приемущество 2"),
    DB_FON_VALUES_27(6, "База данных. FON. MAN. Приемущество 1Х"),
    DB_FON_VALUES_28(6, "База данных. FON. MAN. Приемущество 12"),
    DB_FON_VALUES_29(6, "База данных. FON. MAN. Приемущество Х2"),
    DB_FON_VALUES_30(6, "База данных. FON. MAN. Серия 1"),
    DB_FON_VALUES_31(6, "База данных. FON. MAN. Серия Х"),
    DB_FON_VALUES_32(6, "База данных. FON. MAN. Серия 2"),
    DB_FON_VALUES_33(6, "База данных. FON. MAN. Серия без 1"),
    DB_FON_VALUES_34(6, "База данных. FON. MAN. Серия без Х"),
    DB_FON_VALUES_35(6, "База данных. FON. MAN. Серия без 2"),


    DB_FON_TOURNAMENT_VALUES_0(7, "База данных. FON_TOURNAMENT. WDL. Приемущество 1"),
    DB_FON_TOURNAMENT_VALUES_1(7, "База данных. FON_TOURNAMENT. WDL. Приемущество Х"),
    DB_FON_TOURNAMENT_VALUES_2(7, "База данных. FON_TOURNAMENT. WDL. Приемущество 2"),
    DB_FON_TOURNAMENT_VALUES_3(7, "База данных. FON_TOURNAMENT. WDL. Приемущество 1Х"),
    DB_FON_TOURNAMENT_VALUES_4(7, "База данных. FON_TOURNAMENT. WDL. Приемущество 12"),
    DB_FON_TOURNAMENT_VALUES_5(7, "База данных. FON_TOURNAMENT. WDL. Приемущество Х2"),
    DB_FON_TOURNAMENT_VALUES_6(7, "База данных. FON_TOURNAMENT. WDL. Серия 1"),
    DB_FON_TOURNAMENT_VALUES_7(7, "База данных. FON_TOURNAMENT. WDL. Серия Х"),
    DB_FON_TOURNAMENT_VALUES_8(7, "База данных. FON_TOURNAMENT. WDL. Серия 2"),
    DB_FON_TOURNAMENT_VALUES_9(7, "База данных. FON_TOURNAMENT. WDL. Серия без 1"),
    DB_FON_TOURNAMENT_VALUES_10(7, "База данных. FON_TOURNAMENT. WDL. Серия без Х"),
    DB_FON_TOURNAMENT_VALUES_11(7, "База данных. FON_TOURNAMENT. WDL. Серия без 2"),
    DB_FON_TOURNAMENT_VALUES_12(7, "База данных. FON_TOURNAMENT. FON. Приемущество 1"),
    DB_FON_TOURNAMENT_VALUES_13(7, "База данных. FON_TOURNAMENT. FON. Приемущество Х"),
    DB_FON_TOURNAMENT_VALUES_14(7, "База данных. FON_TOURNAMENT. FON. Приемущество 2"),
    DB_FON_TOURNAMENT_VALUES_15(7, "База данных. FON_TOURNAMENT. FON. Приемущество 1Х"),
    DB_FON_TOURNAMENT_VALUES_16(7, "База данных. FON_TOURNAMENT. FON. Приемущество 12"),
    DB_FON_TOURNAMENT_VALUES_17(7, "База данных. FON_TOURNAMENT. FON. Приемущество Х2"),
    DB_FON_TOURNAMENT_VALUES_18(7, "База данных. FON_TOURNAMENT. FON. Серия 1"),
    DB_FON_TOURNAMENT_VALUES_19(7, "База данных. FON_TOURNAMENT. FON. Серия Х"),
    DB_FON_TOURNAMENT_VALUES_20(7, "База данных. FON_TOURNAMENT. FON. Серия 2"),
    DB_FON_TOURNAMENT_VALUES_21(7, "База данных. FON_TOURNAMENT. FON. Серия без 1"),
    DB_FON_TOURNAMENT_VALUES_22(7, "База данных. FON_TOURNAMENT. FON. Серия без Х"),
    DB_FON_TOURNAMENT_VALUES_23(7, "База данных. FON_TOURNAMENT. FON. Серия без 2"),
    DB_FON_TOURNAMENT_VALUES_24(7, "База данных. FON_TOURNAMENT. MAN. Приемущество 1"),
    DB_FON_TOURNAMENT_VALUES_25(7, "База данных. FON_TOURNAMENT. MAN. Приемущество Х"),
    DB_FON_TOURNAMENT_VALUES_26(7, "База данных. FON_TOURNAMENT. MAN. Приемущество 2"),
    DB_FON_TOURNAMENT_VALUES_27(7, "База данных. FON_TOURNAMENT. MAN. Приемущество 1Х"),
    DB_FON_TOURNAMENT_VALUES_28(7, "База данных. FON_TOURNAMENT. MAN. Приемущество 12"),
    DB_FON_TOURNAMENT_VALUES_29(7, "База данных. FON_TOURNAMENT. MAN. Приемущество Х2"),
    DB_FON_TOURNAMENT_VALUES_30(7, "База данных. FON_TOURNAMENT. MAN. Серия 1"),
    DB_FON_TOURNAMENT_VALUES_31(7, "База данных. FON_TOURNAMENT. MAN. Серия Х"),
    DB_FON_TOURNAMENT_VALUES_32(7, "База данных. FON_TOURNAMENT. MAN. Серия 2"),
    DB_FON_TOURNAMENT_VALUES_33(7, "База данных. FON_TOURNAMENT. MAN. Серия без 1"),
    DB_FON_TOURNAMENT_VALUES_34(7, "База данных. FON_TOURNAMENT. MAN. Серия без Х"),
    DB_FON_TOURNAMENT_VALUES_35(7, "База данных. FON_TOURNAMENT. MAN. Серия без 2"),


    DB_MAN_VALUES_0(8, "База данных. MAN. WDL. Приемущество 1"),
    DB_MAN_VALUES_1(8, "База данных. MAN. WDL. Приемущество Х"),
    DB_MAN_VALUES_2(8, "База данных. MAN. WDL. Приемущество 2"),
    DB_MAN_VALUES_3(8, "База данных. MAN. WDL. Приемущество 1Х"),
    DB_MAN_VALUES_4(8, "База данных. MAN. WDL. Приемущество 12"),
    DB_MAN_VALUES_5(8, "База данных. MAN. WDL. Приемущество Х2"),
    DB_MAN_VALUES_6(8, "База данных. MAN. WDL. Серия 1"),
    DB_MAN_VALUES_7(8, "База данных. MAN. WDL. Серия Х"),
    DB_MAN_VALUES_8(8, "База данных. MAN. WDL. Серия 2"),
    DB_MAN_VALUES_9(8, "База данных. MAN. WDL. Серия без 1"),
    DB_MAN_VALUES_10(8, "База данных. MAN. WDL. Серия без Х"),
    DB_MAN_VALUES_11(8, "База данных. MAN. WDL. Серия без 2"),
    DB_MAN_VALUES_12(8, "База данных. MAN. FON. Приемущество 1"),
    DB_MAN_VALUES_13(8, "База данных. MAN. FON. Приемущество Х"),
    DB_MAN_VALUES_14(8, "База данных. MAN. FON. Приемущество 2"),
    DB_MAN_VALUES_15(8, "База данных. MAN. FON. Приемущество 1Х"),
    DB_MAN_VALUES_16(8, "База данных. MAN. FON. Приемущество 12"),
    DB_MAN_VALUES_17(8, "База данных. MAN. FON. Приемущество Х2"),
    DB_MAN_VALUES_18(8, "База данных. MAN. FON. Серия 1"),
    DB_MAN_VALUES_19(8, "База данных. MAN. FON. Серия Х"),
    DB_MAN_VALUES_20(8, "База данных. MAN. FON. Серия 2"),
    DB_MAN_VALUES_21(8, "База данных. MAN. FON. Серия без 1"),
    DB_MAN_VALUES_22(8, "База данных. MAN. FON. Серия без Х"),
    DB_MAN_VALUES_23(8, "База данных. MAN. FON. Серия без 2"),
    DB_MAN_VALUES_24(8, "База данных. MAN. MAN. Приемущество 1"),
    DB_MAN_VALUES_25(8, "База данных. MAN. MAN. Приемущество Х"),
    DB_MAN_VALUES_26(8, "База данных. MAN. MAN. Приемущество 2"),
    DB_MAN_VALUES_27(8, "База данных. MAN. MAN. Приемущество 1Х"),
    DB_MAN_VALUES_28(8, "База данных. MAN. MAN. Приемущество 12"),
    DB_MAN_VALUES_29(8, "База данных. MAN. MAN. Приемущество Х2"),
    DB_MAN_VALUES_30(8, "База данных. MAN. MAN. Серия 1"),
    DB_MAN_VALUES_31(8, "База данных. MAN. MAN. Серия Х"),
    DB_MAN_VALUES_32(8, "База данных. MAN. MAN. Серия 2"),
    DB_MAN_VALUES_33(8, "База данных. MAN. MAN. Серия без 1"),
    DB_MAN_VALUES_34(8, "База данных. MAN. MAN. Серия без Х"),
    DB_MAN_VALUES_35(8, "База данных. MAN. MAN. Серия без 2"),

    DB_MAN_TOURNAMENT_VALUES_0(9, "База данных. MAN_TOURNAMENT. WDL. Приемущество 1"),
    DB_MAN_TOURNAMENT_VALUES_1(9, "База данных. MAN_TOURNAMENT. WDL. Приемущество Х"),
    DB_MAN_TOURNAMENT_VALUES_2(9, "База данных. MAN_TOURNAMENT. WDL. Приемущество 2"),
    DB_MAN_TOURNAMENT_VALUES_3(9, "База данных. MAN_TOURNAMENT. WDL. Приемущество 1Х"),
    DB_MAN_TOURNAMENT_VALUES_4(9, "База данных. MAN_TOURNAMENT. WDL. Приемущество 12"),
    DB_MAN_TOURNAMENT_VALUES_5(9, "База данных. MAN_TOURNAMENT. WDL. Приемущество Х2"),
    DB_MAN_TOURNAMENT_VALUES_6(9, "База данных. MAN_TOURNAMENT. WDL. Серия 1"),
    DB_MAN_TOURNAMENT_VALUES_7(9, "База данных. MAN_TOURNAMENT. WDL. Серия Х"),
    DB_MAN_TOURNAMENT_VALUES_8(9, "База данных. MAN_TOURNAMENT. WDL. Серия 2"),
    DB_MAN_TOURNAMENT_VALUES_9(9, "База данных. MAN_TOURNAMENT. WDL. Серия без 1"),
    DB_MAN_TOURNAMENT_VALUES_10(9, "База данных. MAN_TOURNAMENT. WDL. Серия без Х"),
    DB_MAN_TOURNAMENT_VALUES_11(9, "База данных. MAN_TOURNAMENT. WDL. Серия без 2"),
    DB_MAN_TOURNAMENT_VALUES_12(9, "База данных. MAN_TOURNAMENT. FON. Приемущество 1"),
    DB_MAN_TOURNAMENT_VALUES_13(9, "База данных. MAN_TOURNAMENT. FON. Приемущество Х"),
    DB_MAN_TOURNAMENT_VALUES_14(9, "База данных. MAN_TOURNAMENT. FON. Приемущество 2"),
    DB_MAN_TOURNAMENT_VALUES_15(9, "База данных. MAN_TOURNAMENT. FON. Приемущество 1Х"),
    DB_MAN_TOURNAMENT_VALUES_16(9, "База данных. MAN_TOURNAMENT. FON. Приемущество 12"),
    DB_MAN_TOURNAMENT_VALUES_17(9, "База данных. MAN_TOURNAMENT. FON. Приемущество Х2"),
    DB_MAN_TOURNAMENT_VALUES_18(9, "База данных. MAN_TOURNAMENT. FON. Серия 1"),
    DB_MAN_TOURNAMENT_VALUES_19(9, "База данных. MAN_TOURNAMENT. FON. Серия Х"),
    DB_MAN_TOURNAMENT_VALUES_20(9, "База данных. MAN_TOURNAMENT. FON. Серия 2"),
    DB_MAN_TOURNAMENT_VALUES_21(9, "База данных. MAN_TOURNAMENT. FON. Серия без 1"),
    DB_MAN_TOURNAMENT_VALUES_22(9, "База данных. MAN_TOURNAMENT. FON. Серия без Х"),
    DB_MAN_TOURNAMENT_VALUES_23(9, "База данных. MAN_TOURNAMENT. FON. Серия без 2"),
    DB_MAN_TOURNAMENT_VALUES_24(9, "База данных. MAN_TOURNAMENT. MAN. Приемущество 1"),
    DB_MAN_TOURNAMENT_VALUES_25(9, "База данных. MAN_TOURNAMENT. MAN. Приемущество Х"),
    DB_MAN_TOURNAMENT_VALUES_26(9, "База данных. MAN_TOURNAMENT. MAN. Приемущество 2"),
    DB_MAN_TOURNAMENT_VALUES_27(9, "База данных. MAN_TOURNAMENT. MAN. Приемущество 1Х"),
    DB_MAN_TOURNAMENT_VALUES_28(9, "База данных. MAN_TOURNAMENT. MAN. Приемущество 12"),
    DB_MAN_TOURNAMENT_VALUES_29(9, "База данных. MAN_TOURNAMENT. MAN. Приемущество Х2"),
    DB_MAN_TOURNAMENT_VALUES_30(9, "База данных. MAN_TOURNAMENT. MAN. Серия 1"),
    DB_MAN_TOURNAMENT_VALUES_31(9, "База данных. MAN_TOURNAMENT. MAN. Серия Х"),
    DB_MAN_TOURNAMENT_VALUES_32(9, "База данных. MAN_TOURNAMENT. MAN. Серия 2"),
    DB_MAN_TOURNAMENT_VALUES_33(9, "База данных. MAN_TOURNAMENT. MAN. Серия без 1"),
    DB_MAN_TOURNAMENT_VALUES_34(9, "База данных. MAN_TOURNAMENT. MAN. Серия без Х"),
    DB_MAN_TOURNAMENT_VALUES_35(9, "База данных. MAN_TOURNAMENT. MAN. Серия без 2"),


    DB_QUEERNESS_0(10, "База данных. QUEERNESS. WDL. Приемущество 1"),
    DB_QUEERNESS_1(10, "База данных. QUEERNESS. WDL. Приемущество Х"),
    DB_QUEERNESS_2(10, "База данных. QUEERNESS. WDL. Приемущество 2"),
    DB_QUEERNESS_3(10, "База данных. QUEERNESS. WDL. Приемущество 1Х"),
    DB_QUEERNESS_4(10, "База данных. QUEERNESS. WDL. Приемущество 12"),
    DB_QUEERNESS_5(10, "База данных. QUEERNESS. WDL. Приемущество Х2"),
    DB_QUEERNESS_6(10, "База данных. QUEERNESS. WDL. Серия 1"),
    DB_QUEERNESS_7(10, "База данных. QUEERNESS. WDL. Серия Х"),
    DB_QUEERNESS_8(10, "База данных. QUEERNESS. WDL. Серия 2"),
    DB_QUEERNESS_9(10, "База данных. QUEERNESS. WDL. Серия без 1"),
    DB_QUEERNESS_10(10, "База данных. QUEERNESS. WDL. Серия без Х"),
    DB_QUEERNESS_11(10, "База данных. QUEERNESS. WDL. Серия без 2"),
    DB_QUEERNESS_12(10, "База данных. QUEERNESS. FON. Приемущество 1"),
    DB_QUEERNESS_13(10, "База данных. QUEERNESS. FON. Приемущество Х"),
    DB_QUEERNESS_14(10, "База данных. QUEERNESS. FON. Приемущество 2"),
    DB_QUEERNESS_15(10, "База данных. QUEERNESS. FON. Приемущество 1Х"),
    DB_QUEERNESS_16(10, "База данных. QUEERNESS. FON. Приемущество 12"),
    DB_QUEERNESS_17(10, "База данных. QUEERNESS. FON. Приемущество Х2"),
    DB_QUEERNESS_18(10, "База данных. QUEERNESS. FON. Серия 1"),
    DB_QUEERNESS_19(10, "База данных. QUEERNESS. FON. Серия Х"),
    DB_QUEERNESS_20(10, "База данных. QUEERNESS. FON. Серия 2"),
    DB_QUEERNESS_21(10, "База данных. QUEERNESS. FON. Серия без 1"),
    DB_QUEERNESS_22(10, "База данных. QUEERNESS. FON. Серия без Х"),
    DB_QUEERNESS_23(10, "База данных. QUEERNESS. FON. Серия без 2"),
    DB_QUEERNESS_24(10, "База данных. QUEERNESS. MAN. Приемущество 1"),
    DB_QUEERNESS_25(10, "База данных. QUEERNESS. MAN. Приемущество Х"),
    DB_QUEERNESS_26(10, "База данных. QUEERNESS. MAN. Приемущество 2"),
    DB_QUEERNESS_27(10, "База данных. QUEERNESS. MAN. Приемущество 1Х"),
    DB_QUEERNESS_28(10, "База данных. QUEERNESS. MAN. Приемущество 12"),
    DB_QUEERNESS_29(10, "База данных. QUEERNESS. MAN. Приемущество Х2"),
    DB_QUEERNESS_30(10, "База данных. QUEERNESS. MAN. Серия 1"),
    DB_QUEERNESS_31(10, "База данных. QUEERNESS. MAN. Серия Х"),
    DB_QUEERNESS_32(10, "База данных. QUEERNESS. MAN. Серия 2"),
    DB_QUEERNESS_33(10, "База данных. QUEERNESS. MAN. Серия без 1"),
    DB_QUEERNESS_34(10, "База данных. QUEERNESS. MAN. Серия без Х"),
    DB_QUEERNESS_35(10, "База данных. QUEERNESS. MAN. Серия без 2"),

    TOURNAMENT_HOME_0(11, "Турнир. Хозяева. Победы - 0"),
    TOURNAMENT_HOME_1(11, "Турнир. Хозяева. Победы - 1"),
    TOURNAMENT_HOME_2(11, "Турнир. Хозяева. Победы - 2"),
    TOURNAMENT_HOME_3(11, "Турнир. Хозяева. Победы - 3"),
    TOURNAMENT_HOME_4(11, "Турнир. Хозяева. Победы - 4"),
    TOURNAMENT_HOME_5(11, "Турнир. Хозяева. Поражения - 0"),
    TOURNAMENT_HOME_6(11, "Турнир. Хозяева. Поражения - 1"),
    TOURNAMENT_HOME_7(11, "Турнир. Хозяева. Поражения - 2"),
    TOURNAMENT_HOME_8(11, "Турнир. Хозяева. Поражения - 3"),
    TOURNAMENT_HOME_9(11, "Турнир. Хозяева. Поражения - 4"),
    TOURNAMENT_HOME_10(11, "Турнир. Хозяева. Ничьи - 0"),
    TOURNAMENT_HOME_11(11, "Турнир. Хозяева. Ничьи - 1"),
    TOURNAMENT_HOME_12(11, "Турнир. Хозяева. Ничьи - 2"),
    TOURNAMENT_HOME_13(11, "Турнир. Хозяева. Ничьи - 3"),
    TOURNAMENT_HOME_14(11, "Турнир. Хозяева. Ничьи - 4"),
    TOURNAMENT_HOME_15(11, "Турнир. Хозяева. Победы подряд - 2"),
    TOURNAMENT_HOME_16(11, "Турнир. Хозяева. Победы подряд - 3"),
    TOURNAMENT_HOME_17(11, "Турнир. Хозяева. Победы подряд - 4"),
    TOURNAMENT_HOME_18(11, "Турнир. Хозяева. Победы подряд - 5"),
    TOURNAMENT_HOME_19(11, "Турнир. Хозяева. Поражения подряд - 2"),
    TOURNAMENT_HOME_20(11, "Турнир. Хозяева. Поражения подряд - 3"),
    TOURNAMENT_HOME_21(11, "Турнир. Хозяева. Поражения подряд - 4"),
    TOURNAMENT_HOME_22(11, "Турнир. Хозяева. Поражения подряд - 5"),
    TOURNAMENT_HOME_23(11, "Турнир. Хозяева. Ничьи подряд - 2"),
    TOURNAMENT_HOME_24(11, "Турнир. Хозяева. Ничьи подряд - 3"),
    TOURNAMENT_HOME_25(11, "Турнир. Хозяева. Ничьи подряд - 4"),
    TOURNAMENT_HOME_26(11, "Турнир. Хозяева. Ничьи подряд - 5"),

    TOURNAMENT_AWAY_0(12, "Турнир. Гости. Победы - 0"),
    TOURNAMENT_AWAY_1(12, "Турнир. Гости. Победы - 1"),
    TOURNAMENT_AWAY_2(12, "Турнир. Гости. Победы - 2"),
    TOURNAMENT_AWAY_3(12, "Турнир. Гости. Победы - 3"),
    TOURNAMENT_AWAY_4(12, "Турнир. Гости. Победы - 4"),
    TOURNAMENT_AWAY_5(12, "Турнир. Гости. Поражения - 0"),
    TOURNAMENT_AWAY_6(12, "Турнир. Гости. Поражения - 1"),
    TOURNAMENT_AWAY_7(12, "Турнир. Гости. Поражения - 2"),
    TOURNAMENT_AWAY_8(12, "Турнир. Гости. Поражения - 3"),
    TOURNAMENT_AWAY_9(12, "Турнир. Гости. Поражения - 4"),
    TOURNAMENT_AWAY_10(12, "Турнир. Гости. Ничьи - 0"),
    TOURNAMENT_AWAY_11(12, "Турнир. Гости. Ничьи - 1"),
    TOURNAMENT_AWAY_12(12, "Турнир. Гости. Ничьи - 2"),
    TOURNAMENT_AWAY_13(12, "Турнир. Гости. Ничьи - 3"),
    TOURNAMENT_AWAY_14(12, "Турнир. Гости. Ничьи - 4"),
    TOURNAMENT_AWAY_15(12, "Турнир. Гости. Победы подряд - 2"),
    TOURNAMENT_AWAY_16(12, "Турнир. Гости. Победы подряд - 3"),
    TOURNAMENT_AWAY_17(12, "Турнир. Гости. Победы подряд - 4"),
    TOURNAMENT_AWAY_18(12, "Турнир. Гости. Победы подряд - 5"),
    TOURNAMENT_AWAY_19(12, "Турнир. Гости. Поражения подряд - 2"),
    TOURNAMENT_AWAY_20(12, "Турнир. Гости. Поражения подряд - 3"),
    TOURNAMENT_AWAY_21(12, "Турнир. Гости. Поражения подряд - 4"),
    TOURNAMENT_AWAY_22(12, "Турнир. Гости. Поражения подряд - 5"),
    TOURNAMENT_AWAY_23(12, "Турнир. Гости. Ничьи подряд - 2"),
    TOURNAMENT_AWAY_24(12, "Турнир. Гости. Ничьи подряд - 3"),
    TOURNAMENT_AWAY_25(12, "Турнир. Гости. Ничьи подряд - 4"),
    TOURNAMENT_AWAY_26(12, "Турнир. Гости. Ничьи подряд - 5"),


    TOURNAMENT_HOME_ONLY_0(13, "Турнир. Хозяева дома. Победы - 0"),
    TOURNAMENT_HOME_ONLY_1(13, "Турнир. Хозяева дома. Победы - 1"),
    TOURNAMENT_HOME_ONLY_2(13, "Турнир. Хозяева дома. Победы - 2"),
    TOURNAMENT_HOME_ONLY_3(13, "Турнир. Хозяева дома. Победы - 3"),
    TOURNAMENT_HOME_ONLY_4(13, "Турнир. Хозяева дома. Победы - 4"),
    TOURNAMENT_HOME_ONLY_5(13, "Турнир. Хозяева дома. Поражения - 0"),
    TOURNAMENT_HOME_ONLY_6(13, "Турнир. Хозяева дома. Поражения - 1"),
    TOURNAMENT_HOME_ONLY_7(13, "Турнир. Хозяева дома. Поражения - 2"),
    TOURNAMENT_HOME_ONLY_8(13, "Турнир. Хозяева дома. Поражения - 3"),
    TOURNAMENT_HOME_ONLY_9(13, "Турнир. Хозяева дома. Поражения - 4"),
    TOURNAMENT_HOME_ONLY_10(13, "Турнир. Хозяева дома. Ничьи - 0"),
    TOURNAMENT_HOME_ONLY_11(13, "Турнир. Хозяева дома. Ничьи - 1"),
    TOURNAMENT_HOME_ONLY_12(13, "Турнир. Хозяева дома. Ничьи - 2"),
    TOURNAMENT_HOME_ONLY_13(13, "Турнир. Хозяева дома. Ничьи - 3"),
    TOURNAMENT_HOME_ONLY_14(13, "Турнир. Хозяева дома. Ничьи - 4"),
    TOURNAMENT_HOME_ONLY_15(13, "Турнир. Хозяева дома. Победы подряд - 2"),
    TOURNAMENT_HOME_ONLY_16(13, "Турнир. Хозяева дома. Победы подряд - 3"),
    TOURNAMENT_HOME_ONLY_17(13, "Турнир. Хозяева дома. Победы подряд - 4"),
    TOURNAMENT_HOME_ONLY_18(13, "Турнир. Хозяева дома. Победы подряд - 5"),
    TOURNAMENT_HOME_ONLY_19(13, "Турнир. Хозяева дома. Поражения подряд - 2"),
    TOURNAMENT_HOME_ONLY_20(13, "Турнир. Хозяева дома. Поражения подряд - 3"),
    TOURNAMENT_HOME_ONLY_21(13, "Турнир. Хозяева дома. Поражения подряд - 4"),
    TOURNAMENT_HOME_ONLY_22(13, "Турнир. Хозяева дома. Поражения подряд - 5"),
    TOURNAMENT_HOME_ONLY_23(13, "Турнир. Хозяева дома. Ничьи подряд - 2"),
    TOURNAMENT_HOME_ONLY_24(13, "Турнир. Хозяева дома. Ничьи подряд - 3"),
    TOURNAMENT_HOME_ONLY_25(13, "Турнир. Хозяева дома. Ничьи подряд - 4"),
    TOURNAMENT_HOME_ONLY_26(13, "Турнир. Хозяева дома. Ничьи подряд - 5"),


    TOURNAMENT_AWAY_ONLY_0(14, "Турнир. Гости в гостях. Победы - 0"),
    TOURNAMENT_AWAY_ONLY_1(14, "Турнир. Гости в гостях. Победы - 1"),
    TOURNAMENT_AWAY_ONLY_2(14, "Турнир. Гости в гостях. Победы - 2"),
    TOURNAMENT_AWAY_ONLY_3(14, "Турнир. Гости в гостях. Победы - 3"),
    TOURNAMENT_AWAY_ONLY_4(14, "Турнир. Гости в гостях. Победы - 4"),
    TOURNAMENT_AWAY_ONLY_5(14, "Турнир. Гости в гостях. Поражения - 0"),
    TOURNAMENT_AWAY_ONLY_6(14, "Турнир. Гости в гостях. Поражения - 1"),
    TOURNAMENT_AWAY_ONLY_7(14, "Турнир. Гости в гостях. Поражения - 2"),
    TOURNAMENT_AWAY_ONLY_8(14, "Турнир. Гости в гостях. Поражения - 3"),
    TOURNAMENT_AWAY_ONLY_9(14, "Турнир. Гости в гостях. Поражения - 4"),
    TOURNAMENT_AWAY_ONLY_10(14, "Турнир. Гости в гостях. Ничьи - 0"),
    TOURNAMENT_AWAY_ONLY_11(14, "Турнир. Гости в гостях. Ничьи - 1"),
    TOURNAMENT_AWAY_ONLY_12(14, "Турнир. Гости в гостях. Ничьи - 2"),
    TOURNAMENT_AWAY_ONLY_13(14, "Турнир. Гости в гостях. Ничьи - 3"),
    TOURNAMENT_AWAY_ONLY_14(14, "Турнир. Гости в гостях. Ничьи - 4"),
    TOURNAMENT_AWAY_ONLY_15(14, "Турнир. Гости в гостях. Победы подряд - 2"),
    TOURNAMENT_AWAY_ONLY_16(14, "Турнир. Гости в гостях. Победы подряд - 3"),
    TOURNAMENT_AWAY_ONLY_17(14, "Турнир. Гости в гостях. Победы подряд - 4"),
    TOURNAMENT_AWAY_ONLY_18(14, "Турнир. Гости в гостях. Победы подряд - 5"),
    TOURNAMENT_AWAY_ONLY_19(14, "Турнир. Гости в гостях. Поражения подряд - 2"),
    TOURNAMENT_AWAY_ONLY_20(14, "Турнир. Гости в гостях. Поражения подряд - 3"),
    TOURNAMENT_AWAY_ONLY_21(14, "Турнир. Гости в гостях. Поражения подряд - 4"),
    TOURNAMENT_AWAY_ONLY_22(14, "Турнир. Гости в гостях. Поражения подряд - 5"),
    TOURNAMENT_AWAY_ONLY_23(14, "Турнир. Гости в гостях. Ничьи подряд - 2"),
    TOURNAMENT_AWAY_ONLY_24(14, "Турнир. Гости в гостях. Ничьи подряд - 3"),
    TOURNAMENT_AWAY_ONLY_25(14, "Турнир. Гости в гостях. Ничьи подряд - 4"),
    TOURNAMENT_AWAY_ONLY_26(14, "Турнир. Гости в гостях. Ничьи подряд - 5"),

    TOURNAMENT_H2H_0(15, "Турнир. Личные встречи. Приемущество 1"),
    TOURNAMENT_H2H_1(15, "Турнир. Личные встречи. Приемущество Х"),
    TOURNAMENT_H2H_2(15, "Турнир. Личные встречи. Приемущество 2"),
    TOURNAMENT_H2H_3(15, "Турнир. Личные встречи. Приемущество 1Х"),
    TOURNAMENT_H2H_4(15, "Турнир. Личные встречи. Приемущество 12"),
    TOURNAMENT_H2H_5(15, "Турнир. Личные встречи. Приемущество Х2"),
    TOURNAMENT_H2H_6(15, "Турнир. Личные встречи. Серия 1"),
    TOURNAMENT_H2H_7(15, "Турнир. Личные встречи. Серия Х"),
    TOURNAMENT_H2H_8(15, "Турнир. Личные встречи. Серия 2"),
    TOURNAMENT_H2H_9(15, "Турнир. Личные встречи. Серия без 1"),
    TOURNAMENT_H2H_10(15, "Турнир. Личные встречи. Серия без Х"),
    TOURNAMENT_H2H_11(15, "Турнир. Личные встречи. Серия без 2"),

    FEATURE_0(16, "Наблюдения. Явный фаворит 1"),
    FEATURE_1(16, "Наблюдения. Явный фаворит X"),
    FEATURE_2(16, "Наблюдения. Явный фаворит 2"),
    FEATURE_3(16, "Наблюдения. Ничья - пулл FON"),
    FEATURE_4(16, "Наблюдения. Ничья - пулл MAN");






//    TOUR_MAN_R_SOME_GAMES_WITHOUT_MAN_POOL("Серия игр без MAN пула в турнире"),
//    TOUR_FON_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без FON мидпулла в турнире"),
//    TOUR_FON_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без FON противопула в турнире"),
//    TOUR_FON_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием FON пула в турнире"),
//    TOUR_FON_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием FON миддлпула в турнире"),
//    TOUR_FON_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием FON противопулапула в турнире"),
//    TOUR_FON_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из FON пула в турнире"),
//    TOUR_FON_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из FON миддлпула в турнире"),
//    TOUR_FON_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из FON противопула в турнире"),
//
//    TOUR_MAN_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр без MAN пула в турнире"),
//    TOUR_MAN_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без MAN мидпулла в турнире"),
//    TOUR_MAN_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без MAN противопула в турнире"),
//    TOUR_MAN_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием MAN пула в турнире"),
//    TOUR_MAN_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием MAN миддлпула в турнире"),
//    TOUR_MAN_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием MAN противопулапула в турнире"),
//    TOUR_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из MAN пула в турнире"),
//    TOUR_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из MAN миддлпула в турнире"),
//    TOUR_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из MAN противопула в турнире"),
//
//    TOUR_HOME_WDL_R_SOME_GAMES_WITHOUT_HOME_WIN("Серия игр хозяев без побед в турнире"),
//    TOUR_HOME_WDL_R_SOME_GAMES_WITHOUT_DRAW("Серия игр хозяев без ничьих в турнире"),
//    TOUR_HOME_WDL_R_SOME_GAMES_WITHOUT_LOSE("Серия игр хозяев без поражений в турнире"),
//    TOUR_HOME_WDL_R_SOME_GAMES_WITH_HOME_WIN("Серия игр хозяев с преобладанием побед хозяев в турнире"),
//    TOUR_HOME_WDL_R_SOME_GAMES_WITH_DRAW_WIN("Серия игр хозяев с преобладанием ничьих в турнире"),
//    TOUR_HOME_WDL_R_SOME_GAMES_WITH_AWAY_WIN("Серия игр хозяев с преобладанием побед гостей в турнире"),
//    TOUR_HOME_WDL_ROW_R_SOME_GAMES_HOME_IN_ROW("Серия игр хозяев из побед хозяев подряд в турнире"),
//    TOUR_HOME_WDL_ROW_R_SOME_GAMES_DRAW_IN_ROW("Серия игр хозяев из ничьих подряд в турнире"),
//    TOUR_HOME_WDL_ROW_R_SOME_GAMES_AWAY_IN_ROW("Серия игр хозяев из побед гостей подряд в турнире"),
//
//    TOUR_HOME_FON_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр хозяев без FON пула в турнире"),
//    TOUR_HOME_FON_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр хозяев без FON мидпулла в турнире"),
//    TOUR_HOME_FON_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр хозяев без FON противопула в турнире"),
//    TOUR_HOME_FON_R_SOME_GAMES_WITH_FON_POOL("Серия игр хозяев с преобладанием FON пула в турнире"),
//    TOUR_HOME_FON_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр хозяев с преобладанием FON миддлпула в турнире"),
//    TOUR_HOME_FON_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр хозяев с преобладанием FON противопулапула в турнире"),
//    TOUR_HOME_FON_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр хозяев из FON пула в турнире"),
//    TOUR_HOME_FON_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр хозяев из FON миддлпула в турнире"),
//    TOUR_HOME_FON_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр хозяев из FON противопула в турнире"),
//
//    TOUR_HOME_MAN_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр хозяев без MAN пула в турнире"),
//    TOUR_HOME_MAN_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр хозяев без MAN мидпулла в турнире"),
//    TOUR_HOME_MAN_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр хозяев без MAN противопула в турнире"),
//    TOUR_HOME_MAN_R_SOME_GAMES_WITH_FON_POOL("Серия игр хозяев с преобладанием MAN пула в турнире"),
//    TOUR_HOME_MAN_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр хозяев с преобладанием MAN миддлпула в турнире"),
//    TOUR_HOME_MAN_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр хозяев с преобладанием MAN противопулапула в турнире"),
//    TOUR_HOME_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр хозяев из MAN пула в турнире"),
//    TOUR_HOME_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр хозяев из MAN миддлпула в турнире"),
//    TOUR_HOME_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр хозяев из MAN противопула в турнире"),
//
//    TOUR_HOME_TEAM_HOME_WDL_R_SOME_GAMES_WITHOUT_HOME_WIN("Серия игр хозяев на своем поле без побед в турнире"),
//    TOUR_HOME_TEAM_HOME_WDL_R_SOME_GAMES_WITHOUT_DRAW("Серия игр хозяев на своем поле без ничьих в турнире"),
//    TOUR_HOME_TEAM_HOME_WDL_R_SOME_GAMES_WITHOUT_LOSE("Серия игр хозяев на своем поле без поражений в турнире"),
//    TOUR_HOME_TEAM_HOME_WDL_R_SOME_GAMES_WITH_HOME_WIN("Серия игр хозяев на своем поле с преобладанием побед хозяев в турнире"),
//    TOUR_HOME_TEAM_HOME_WDL_R_SOME_GAMES_WITH_DRAW_WIN("Серия игр хозяев на своем поле с преобладанием ничьих в турнире"),
//    TOUR_HOME_TEAM_HOME_WDL_R_SOME_GAMES_WITH_AWAY_WIN("Серия игр хозяев на своем поле с преобладанием побед гостей в турнире"),
//    TOUR_HOME_TEAM_HOME_WDL_ROW_R_SOME_GAMES_HOME_IN_ROW("Серия игр хозяев на своем поле из побед хозяев подряд в турнире"),
//    TOUR_HOME_TEAM_HOME_WDL_ROW_R_SOME_GAMES_DRAW_IN_ROW("Серия игр хозяев на своем поле из ничьих подряд в турнире"),
//    TOUR_HOME_TEAM_HOME_WDL_ROW_R_SOME_GAMES_AWAY_IN_ROW("Серия игр хозяев на своем поле из побед гостей подряд в турнире"),
//
//
//    TOUR_HOME_TEAM_HOME_FON_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр хозяев на своем поле без FON пула в турнире"),
//    TOUR_HOME_TEAM_HOME_FON_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр хозяев на своем поле без FON мидпулла в турнире"),
//    TOUR_HOME_TEAM_HOME_FON_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр хозяев на своем поле без FON противопула в турнире"),
//    TOUR_HOME_TEAM_HOME_FON_R_SOME_GAMES_WITH_FON_POOL("Серия игр хозяев на своем поле с преобладанием FON пула в турнире"),
//    TOUR_HOME_TEAM_HOME_FON_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр хозяев на своем поле с преобладанием FON миддлпула в турнире"),
//    TOUR_HOME_TEAM_HOME_FON_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр хозяев на своем поле с преобладанием FON противопулапула в турнире"),
//    TOUR_HOME_TEAM_HOME_FON_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр хозяев на своем поле из FON пула в турнире"),
//    TOUR_HOME_TEAM_HOME_FON_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр хозяев на своем поле из FON миддлпула в турнире"),
//    TOUR_HOME_TEAM_HOME_FON_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр хозяев на своем поле из FON противопула в турнире"),
//
//    TOUR_HOME_TEAM_HOME_MAN_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр хозяев на своем поле без MAN пула в турнире"),
//    TOUR_HOME_TEAM_HOME_MAN_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр хозяев на своем поле без MAN мидпулла в турнире"),
//    TOUR_HOME_TEAM_HOME_MAN_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр хозяев на своем поле без MAN противопула в турнире"),
//    TOUR_HOME_TEAM_HOME_MAN_R_SOME_GAMES_WITH_FON_POOL("Серия игр хозяев на своем поле с преобладанием MAN пула в турнире"),
//    TOUR_HOME_TEAM_HOME_MAN_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр хозяев на своем поле с преобладанием MAN миддлпула в турнире"),
//    TOUR_HOME_TEAM_HOME_MAN_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр хозяев на своем поле с преобладанием MAN противопулапула в турнире"),
//    TOUR_HOME_TEAM_HOME_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр хозяев на своем поле из MAN пула в турнире"),
//    TOUR_HOME_TEAM_HOME_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр хозяев на своем поле из MAN миддлпула в турнире"),
//    TOUR_HOME_TEAM_HOME_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр хозяев на своем поле из MAN противопула в турнире"),
//
//
//    TOUR_AWAY_WDL_R_SOME_GAMES_WITHOUT_HOME_WIN("Серия игр гостей без побед в турнире"),
//    TOUR_AWAY_WDL_R_SOME_GAMES_WITHOUT_DRAW("Серия игр гостей без ничьих в турнире"),
//    TOUR_AWAY_WDL_R_SOME_GAMES_WITHOUT_LOSE("Серия игр гостей без поражений в турнире"),
//    TOUR_AWAY_WDL_R_SOME_GAMES_WITH_HOME_WIN("Серия игр гостей с преобладанием побед хозяев в турнире"),
//    TOUR_AWAY_WDL_R_SOME_GAMES_WITH_DRAW_WIN("Серия игр гостей с преобладанием ничьих в турнире"),
//    TOUR_AWAY_WDL_R_SOME_GAMES_WITH_AWAY_WIN("Серия игр гостей с преобладанием побед гостей в турнире"),
//    TOUR_AWAY_WDL_ROW_R_SOME_GAMES_HOME_IN_ROW("Серия игр гостей из побед хозяев подряд в турнире"),
//    TOUR_AWAY_WDL_ROW_R_SOME_GAMES_DRAW_IN_ROW("Серия игр гостей из ничьих подряд в турнире"),
//    TOUR_AWAY_WDL_ROW_R_SOME_GAMES_AWAY_IN_ROW("Серия игр гостей из побед гостей подряд в турнире"),
//
//
//    TOUR_AWAY_FON_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр гостей без FON пула в турнире"),
//    TOUR_AWAY_FON_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр гостей без FON мидпулла в турнире"),
//    TOUR_AWAY_FON_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр гостей без FON противопула в турнире"),
//    TOUR_AWAY_FON_R_SOME_GAMES_WITH_FON_POOL("Серия игр гостей с преобладанием FON пула в турнире"),
//    TOUR_AWAY_FON_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр гостей с преобладанием FON миддлпула в турнире"),
//    TOUR_AWAY_FON_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр гостей с преобладанием FON противопулапула в турнире"),
//    TOUR_AWAY_FON_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр гостей из FON пула в турнире"),
//    TOUR_AWAY_FON_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр гостей из FON миддлпула в турнире"),
//    TOUR_AWAY_FON_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр гостей из FON противопула в турнире"),
//
//    TOUR_AWAY_MAN_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр гостей без MAN пула в турнире"),
//    TOUR_AWAY_MAN_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр гостей без MAN мидпулла в турнире"),
//    TOUR_AWAY_MAN_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр гостей без MAN противопула в турнире"),
//    TOUR_AWAY_MAN_R_SOME_GAMES_WITH_FON_POOL("Серия игр гостей с преобладанием MAN пула в турнире"),
//    TOUR_AWAY_MAN_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр гостей с преобладанием MAN миддлпула в турнире"),
//    TOUR_AWAY_MAN_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр гостей с преобладанием MAN противопулапула в турнире"),
//    TOUR_AWAY_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр гостей из MAN пула в турнире"),
//    TOUR_AWAY_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр гостей из MAN миддлпула в турнире"),
//    TOUR_AWAY_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр гостей из MAN противопула в турнире"),
//
//
//    TOUR_AWAY_TEAM_AWAY_WDL_R_SOME_GAMES_WITHOUT_HOME_WIN("Серия игр гостей на выезде без побед в турнире"),
//    TOUR_AWAY_TEAM_AWAY_WDL_R_SOME_GAMES_WITHOUT_DRAW("Серия игр гостей на выезде без ничьих в турнире"),
//    TOUR_AWAY_TEAM_AWAY_WDL_R_SOME_GAMES_WITHOUT_LOSE("Серия игр гостей на выезде без поражений в турнире"),
//    TOUR_AWAY_TEAM_AWAY_WDL_R_SOME_GAMES_WITH_HOME_WIN("Серия игр гостей на выезде с преобладанием побед хозяев в турнире"),
//    TOUR_AWAY_TEAM_AWAY_WDL_R_SOME_GAMES_WITH_DRAW_WIN("Серия игр гостей на выезде с преобладанием ничьих в турнире"),
//    TOUR_AWAY_TEAM_AWAY_WDL_R_SOME_GAMES_WITH_AWAY_WIN("Серия игр гостей на выезде с преобладанием побед гостей в турнире"),
//    TOUR_AWAY_TEAM_AWAY_WDL_ROW_R_SOME_GAMES_HOME_IN_ROW("Серия игр гостей на выезде из побед хозяев подряд в турнире"),
//    TOUR_AWAY_TEAM_AWAY_WDL_ROW_R_SOME_GAMES_DRAW_IN_ROW("Серия игр гостей на выезде из ничьих подряд в турнире"),
//    TOUR_AWAY_TEAM_AWAY_WDL_ROW_R_SOME_GAMES_AWAY_IN_ROW("Серия игр гостей на выезде из побед гостей подряд в турнире"),
//
//    TOUR_AWAY_TEAM_AWAY_FON_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр гостей на выезде без FON пула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_FON_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр гостей на выезде без FON мидпулла в турнире"),
//    TOUR_AWAY_TEAM_AWAY_FON_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр гостей на выезде без FON противопула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_FON_R_SOME_GAMES_WITH_FON_POOL("Серия игр гостей на выезде с преобладанием FON пула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_FON_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр гостей на выезде с преобладанием FON миддлпула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_FON_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр гостей на выезде с преобладанием FON противопулапула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_FON_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр гостей на выезде из FON пула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_FON_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр гостей на выезде из FON миддлпула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_FON_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр гостей на выезде из FON противопула в турнире"),
//
//    TOUR_AWAY_TEAM_AWAY_MAN_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр гостей на выезде без MAN пула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_MAN_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр гостей на выезде без MAN мидпулла в турнире"),
//    TOUR_AWAY_TEAM_AWAY_MAN_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр гостей на выезде без MAN противопула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_MAN_R_SOME_GAMES_WITH_FON_POOL("Серия игр гостей на выезде с преобладанием MAN пула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_MAN_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр гостей на выезде с преобладанием MAN миддлпула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_MAN_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр гостей на выезде с преобладанием MAN противопулапула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр гостей на выезде из MAN пула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр гостей на выезде из MAN миддлпула в турнире"),
//    TOUR_AWAY_TEAM_AWAY_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр гостей на выезде из MAN противопула в турнире"),
//
//
//    FON_WDL_R_SOME_GAMES_WITHOUT_HOME_WIN("Серия игр без побед хозяев"),
//    FON_WDL_R_SOME_GAMES_WITHOUT_DRAW("Серия игр без ничьих"),
//    FON_WDL_R_SOME_GAMES_WITHOUT_AWAY_WIN("Серия игр без побед гостей"),
//    FON_WDL_R_SOME_GAMES_WITH_HOME_WIN("Серия игр с преобладанием побед хозяев"),
//    FON_WDL_R_SOME_GAMES_WITH_DRAW_WIN("Серия игр с преобладанием ничьих"),
//    FON_WDL_R_SOME_GAMES_WITH_AWAY_WIN("Серия игр с преобладанием побед гостей"),
//    FON_WDL_ROW_R_SOME_GAMES_HOME_IN_ROW("Серия из побед хозяев подряд"),
//    FON_WDL_ROW_R_SOME_GAMES_DRAW_IN_ROW("Серия из ничьих подряд"),
//    FON_WDL_ROW_R_SOME_GAMES_AWAY_IN_ROW("Серия из побед гостей подряд"),
//
//    FON_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр без FON пула"),
//    FON_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без FON мидпулла"),
//    FON_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без FON противопула"),
//    FON_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием FON пула"),
//    FON_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием FON миддлпула"),
//    FON_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием FON противопулапула"),
//    FON_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из FON пула"),
//    FON_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из FON миддлпула"),
//    FON_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из FON противопула"),
//
//
//    FON_MAN_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр без MAN пула"),
//    FON_MAN_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без MAN мидпулла"),
//    FON_MAN_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без MAN противопула"),
//    FON_MAN_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием MAN пула"),
//    FON_MAN_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием MAN миддлпула"),
//    FON_MAN_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием MAN противопулапула"),
//    FON_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из MAN пула"),
//    FON_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из MAN миддлпула"),
//    FON_MAN_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из MAN противопула"),
//
//
//    //there
//    FON_TOUR_WDL_R_SOME_GAMES_WITHOUT_HOME_WIN("Серия игр без побед хозяев"),
//    FON_TOUR_WDL_R_SOME_GAMES_WITHOUT_DRAW("Серия игр без ничьих"),
//    FON_TOUR_WDL_R_SOME_GAMES_WITHOUT_AWAY_WIN("Серия игр без побед гостей"),
//    FON_TOUR_WDL_R_SOME_GAMES_WITH_HOME_WIN("Серия игр с преобладанием побед хозяев"),
//    FON_TOUR_WDL_R_SOME_GAMES_WITH_DRAW_WIN("Серия игр с преобладанием ничьих"),
//    FON_TOUR_WDL_R_SOME_GAMES_WITH_AWAY_WIN("Серия игр с преобладанием побед гостей"),
//    FON_TOUR_WDL_ROW_R_SOME_GAMES_HOME_IN_ROW("Серия из побед хозяев подряд"),
//    FON_TOUR_WDL_ROW_R_SOME_GAMES_DRAW_IN_ROW("Серия из ничьих подряд"),
//    FON_TOUR_WDL_ROW_R_SOME_GAMES_AWAY_IN_ROW("Серия из побед гостей подряд"),
//
//    FON_TOUR_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр без FON пула"),
//    FON_TOUR_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без FON мидпулла"),
//    FON_TOUR_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без FON противопула"),
//    FON_TOUR_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием FON пула"),
//    FON_TOUR_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием FON миддлпула"),
//    FON_TOUR_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием FON противопулапула"),
//    FON_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из FON пула"),
//    FON_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из FON миддлпула"),
//    FON_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из FON противопула"),
//
//
//    FON_MAN_TOUR_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр без MAN пула"),
//    FON_MAN_TOUR_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без MAN мидпулла"),
//    FON_MAN_TOUR_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без MAN противопула"),
//    FON_MAN_TOUR_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием MAN пула"),
//    FON_MAN_TOUR_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием MAN миддлпула"),
//    FON_MAN_TOUR_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием MAN противопулапула"),
//    FON_MAN_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из MAN пула"),
//    FON_MAN_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из MAN миддлпула"),
//    FON_MAN_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из MAN противопула"),
//
//
//    MAN_WDL_R_SOME_GAMES_WITHOUT_HOME_WIN("Серия игр без побед хозяев"),
//    MAN_WDL_R_SOME_GAMES_WITHOUT_DRAW("Серия игр без ничьих"),
//    MAN_WDL_R_SOME_GAMES_WITHOUT_AWAY_WIN("Серия игр без побед гостей"),
//    MAN_WDL_R_SOME_GAMES_WITH_HOME_WIN("Серия игр с преобладанием побед хозяев"),
//    MAN_WDL_R_SOME_GAMES_WITH_DRAW_WIN("Серия игр с преобладанием ничьих"),
//    MAN_WDL_R_SOME_GAMES_WITH_AWAY_WIN("Серия игр с преобладанием побед гостей"),
//    MAN_WDL_ROW_R_SOME_GAMES_HOME_IN_ROW("Серия из побед хозяев подряд"),
//    MAN_WDL_ROW_R_SOME_GAMES_DRAW_IN_ROW("Серия из ничьих подряд"),
//    MAN_WDL_ROW_R_SOME_GAMES_AWAY_IN_ROW("Серия из побед гостей подряд"),
//
//    MAN_FON_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр без FON пула"),
//    MAN_FON_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без FON мидпулла"),
//    MAN_FON_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без FON противопула"),
//    MAN_FON_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием FON пула"),
//    MAN_FON_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием FON миддлпула"),
//    MAN_FON_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием FON противопулапула"),
//    MAN_FON_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из FON пула"),
//    MAN_FON_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из FON миддлпула"),
//    MAN_FON_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из FON противопула"),
//
//    MAN_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр без MAN пула"),
//    MAN_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без MAN мидпулла"),
//    MAN_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без MAN противопула"),
//    MAN_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием MAN пула"),
//    MAN_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием MAN миддлпула"),
//    MAN_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием MAN противопулапула"),
//    MAN_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из MAN пула"),
//    MAN_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из MAN миддлпула"),
//    MAN_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из MAN противопула"),
//
//
//    MAN_TOUR_WDL_R_SOME_GAMES_WITHOUT_HOME_WIN("Серия игр без побед хозяев"),
//    MAN_TOUR_WDL_R_SOME_GAMES_WITHOUT_DRAW("Серия игр без ничьих"),
//    MAN_TOUR_WDL_R_SOME_GAMES_WITHOUT_AWAY_WIN("Серия игр без побед гостей"),
//    MAN_TOUR_WDL_R_SOME_GAMES_WITH_HOME_WIN("Серия игр с преобладанием побед хозяев"),
//    MAN_TOUR_WDL_R_SOME_GAMES_WITH_DRAW_WIN("Серия игр с преобладанием ничьих"),
//    MAN_TOUR_WDL_R_SOME_GAMES_WITH_AWAY_WIN("Серия игр с преобладанием побед гостей"),
//    MAN_TOUR_WDL_ROW_R_SOME_GAMES_HOME_IN_ROW("Серия из побед хозяев подряд"),
//    MAN_TOUR_WDL_ROW_R_SOME_GAMES_DRAW_IN_ROW("Серия из ничьих подряд"),
//    MAN_TOUR_WDL_ROW_R_SOME_GAMES_AWAY_IN_ROW("Серия из побед гостей подряд"),
//
//    MAN_FON_TOUR_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр без FON пула"),
//    MAN_FON_TOUR_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без FON мидпулла"),
//    MAN_FON_TOUR_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без FON противопула"),
//    MAN_FON_TOUR_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием FON пула"),
//    MAN_FON_TOUR_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием FON миддлпула"),
//    MAN_FON_TOUR_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием FON противопулапула"),
//    MAN_FON_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из FON пула"),
//    MAN_FON_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из FON миддлпула"),
//    MAN_FON_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из FON противопула"),
//
//
//    MAN_TOUR_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр без MAN пула"),
//    MAN_TOUR_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр без MAN мидпулла"),
//    MAN_TOUR_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр без MAN противопула"),
//    MAN_TOUR_R_SOME_GAMES_WITH_FON_POOL("Серия игр с преобладанием MAN пула"),
//    MAN_TOUR_R_SOME_GAMES_WITH_FON_MIDDLE("Серия игр с преобладанием MAN миддлпула"),
//    MAN_TOUR_R_SOME_GAMES_WITH_FON_UNPOOL("Серия игр с преобладанием MAN противопулапула"),
//    MAN_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_POOL("Серия игр из MAN пула"),
//    MAN_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_MIDDLE("Серия игр из MAN миддлпула"),
//    MAN_TOUR_ROW_R_SOME_GAMES_WITHOUT_FON_UNPOOL("Серия игр из MAN противопула"),
//
//
//    /**
//     * Статистика команд по данным турнирной таблицы
//     */
//    WDL_HOME_R_TEAM_0_WIN("Хозяева - 0 побед в 5 матчах"),
//    WDL_HOME_R_TEAM_1_WIN("Хозяева - 1 победа в 5 матчах"),
//    WDL_HOME_R_TEAM_2_WIN("Хозяева - 2 победы в 5 матчах"),
//    WDL_HOME_R_TEAM_3_WIN("Хозяева - 3 победы в 5 матчах"),
//    WDL_HOME_R_TEAM_4_WIN("Хозяева - 4 победы в 5 матчах"),
//    WDL_HOME_R_TEAM_2_WIN_IN_ROW("Хозяева - 2 победы подряд"),
//    WDL_HOME_R_TEAM_3_WIN_IN_ROW("Хозяева - 3 победы подряд"),
//    WDL_HOME_R_TEAM_4_WIN_IN_ROW("Хозяева - 4 победы подряд"),
//    WDL_HOME_R_TEAM_5_WIN_IN_ROW("Хозяева - 5 победы подряд"),
//    WDL_HOME_TEAM_HOME_R_0_WIN("Хозяева дома - 0 побед в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_1_WIN("Хозяева дома - 1 победа в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_2_WIN("Хозяева дома - 2 победы в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_3_WIN("Хозяева дома - 3 победы в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_4_WIN("Хозяева дома - 4 победы в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_2_WIN_IN_ROW("Хозяева дома - 2 победы подряд"),
//    WDL_HOME_TEAM_HOME_R_3_WIN_IN_ROW("Хозяева дома - 3 победы подряд"),
//    WDL_HOME_TEAM_HOME_R_4_WIN_IN_ROW("Хозяева дома - 4 победы подряд"),
//    WDL_HOME_TEAM_HOME_R_5_WIN_IN_ROW("Хозяева дома - 5 победы подряд"),
//    WDL_HOME_R_TEAM_0_DRAW("Хозяева - 0 ничьих в 5 матчах"),
//    WDL_HOME_R_TEAM_1_DRAW("Хозяева - 1 ничья в 5 матчах"),
//    WDL_HOME_R_TEAM_2_DRAW("Хозяева - 2 ничьи в 5 матчах"),
//    WDL_HOME_R_TEAM_3_DRAW("Хозяева - 3 ничьи в 5 матчах"),
//    WDL_HOME_R_TEAM_4_DRAW("Хозяева - 4 ничьи в 5 матчах"),
//    WDL_HOME_R_TEAM_2_DRAW_IN_ROW("Хозяева - 2 ничьи подряд"),
//    WDL_HOME_R_TEAM_3_DRAW_IN_ROW("Хозяева - 3 ничьи подряд"),
//    WDL_HOME_R_TEAM_4_DRAW_IN_ROW("Хозяева - 4 ничьи подряд"),
//    WDL_HOME_R_TEAM_5_DRAW_IN_ROW("Хозяева - 5 ничьи подряд"),
//    WDL_HOME_TEAM_HOME_R_0_DRAW("Хозяева дома - 0 ничьих в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_1_DRAW("Хозяева дома - 1 ничья в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_2_DRAW("Хозяева дома - 2 ничьи в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_3_DRAW("Хозяева дома - 3 ничьи в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_4_DRAW("Хозяева дома - 4 ничьи в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_2_DRAW_IN_ROW("Хозяева дома - 2 ничьи подряд"),
//    WDL_HOME_TEAM_HOME_R_3_DRAW_IN_ROW("Хозяева дома - 3 ничьи подряд"),
//    WDL_HOME_TEAM_HOME_R_4_DRAW_IN_ROW("Хозяева дома - 4 ничьи подряд"),
//    WDL_HOME_TEAM_HOME_R_5_DRAW_IN_ROW("Хозяева дома - 5 ничьи подряд"),
//    WDL_HOME_R_TEAM_0_LOSE("Хозяева - 0 поражений в 5 матчах"),
//    WDL_HOME_R_TEAM_1_LOSE("Хозяева - 1 поражение в 5 матчах"),
//    WDL_HOME_R_TEAM_2_LOSE("Хозяева - 2 поражений в 5 матчах"),
//    WDL_HOME_R_TEAM_3_LOSE("Хозяева - 3 поражений в 5 матчах"),
//    WDL_HOME_R_TEAM_4_LOSE("Хозяева - 4 поражений в 5 матчах"),
//    WDL_HOME_R_TEAM_2_LOSE_IN_ROW("Хозяева - 2 поражений подряд"),
//    WDL_HOME_R_TEAM_3_LOSE_IN_ROW("Хозяева - 3 поражений подряд"),
//    WDL_HOME_R_TEAM_4_LOSE_IN_ROW("Хозяева - 4 поражений подряд"),
//    WDL_HOME_R_TEAM_5_LOSE_IN_ROW("Хозяева - 5 поражений подряд"),
//    WDL_HOME_TEAM_HOME_R_0_LOSE("Хозяева дома - 0 поражений в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_1_LOSE("Хозяева дома - 1 поражение в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_2_LOSE("Хозяева дома - 2 поражений в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_3_LOSE("Хозяева дома - 3 поражений в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_4_LOSE("Хозяева дома - 4 поражений в 5 матчах"),
//    WDL_HOME_TEAM_HOME_R_2_LOSE_IN_ROW("Хозяева дома - 2 поражений подряд"),
//    WDL_HOME_TEAM_HOME_R_3_LOSE_IN_ROW("Хозяева дома - 3 поражений подряд"),
//    WDL_HOME_TEAM_HOME_R_4_LOSE_IN_ROW("Хозяева дома - 4 поражений подряд"),
//    WDL_HOME_TEAM_HOME_R_5_LOSE_IN_ROW("Хозяева дома - 5 поражений подряд"),
//    WDL_AWAY_R_TEAM_0_WIN("Гости - 0 побед в 5 матчах"),
//    WDL_AWAY_R_TEAM_1_WIN("Гости - 1 победа в 5 матчах"),
//    WDL_AWAY_R_TEAM_2_WIN("Гости - 2 победы в 5 матчах"),
//    WDL_AWAY_R_TEAM_3_WIN("Гости - 3 победы в 5 матчах"),
//    WDL_AWAY_R_TEAM_4_WIN("Гости - 4 победы в 5 матчах"),
//    WDL_AWAY_R_TEAM_2_WIN_IN_ROW("Гости - 2 победы подряд"),
//    WDL_AWAY_R_TEAM_3_WIN_IN_ROW("Гости - 3 победы подряд"),
//    WDL_AWAY_R_TEAM_4_WIN_IN_ROW("Гости - 4 победы подряд"),
//    WDL_AWAY_R_TEAM_5_WIN_IN_ROW("Гости - 5 победы подряд"),
//    WDL_AWAY_TEAM_AWAY_R_0_WIN("Гости на выезде - 0 побед в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_1_WIN("Гости на выезде - 1 победа в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_2_WIN("Гости на выезде - 2 победы в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_3_WIN("Гости на выезде - 3 победы в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_4_WIN("Гости на выезде - 4 победы в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_2_WIN_IN_ROW("Гости на выезде - 2 победы подряд"),
//    WDL_AWAY_TEAM_AWAY_R_3_WIN_IN_ROW("Гости на выезде - 3 победы подряд"),
//    WDL_AWAY_TEAM_AWAY_R_4_WIN_IN_ROW("Гости на выезде - 4 победы подряд"),
//    WDL_AWAY_TEAM_AWAY_R_5_WIN_IN_ROW("Гости на выезде - 5 победы подряд"),
//    WDL_AWAY_TEAM_R_0_DRAW("Гости - 0 ничьих в 5 матчах"),
//    WDL_AWAY_TEAM_R_1_DRAW("Гости - 1 ничья в 5 матчах"),
//    WDL_AWAY_TEAM_R_2_DRAW("Гости - 2 ничьи в 5 матчах"),
//    WDL_AWAY_TEAM_R_3_DRAW("Гости - 3 ничьи в 5 матчах"),
//    WDL_AWAY_TEAM_R_4_DRAW("Гости - 4 ничьи в 5 матчах"),
//    WDL_AWAY_TEAM_R_2_DRAW_IN_ROW("Гости - 2 ничьи подряд"),
//    WDL_AWAY_TEAM_R_3_DRAW_IN_ROW("Гости - 3 ничьи подряд"),
//    WDL_AWAY_TEAM_R_4_DRAW_IN_ROW("Гости - 4 ничьи подряд"),
//    WDL_AWAY_TEAM_R_5_DRAW_IN_ROW("Гости - 5 ничьи подряд"),
//    WDL_AWAY_TEAM_AWAY_R_0_DRAW("Гости на выезде - 0 ничьих в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_1_DRAW("Гости на выезде - 1 ничья в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_2_DRAW("Гости на выезде - 2 ничьи в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_3_DRAW("Гости на выезде - 3 ничьи в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_4_DRAW("Гости на выезде - 4 ничьи в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_2_DRAW_IN_ROW("Гости на выезде - 2 ничьи подряд"),
//    WDL_AWAY_TEAM_AWAY_R_3_DRAW_IN_ROW("Гости на выезде - 3 ничьи подряд"),
//    WDL_AWAY_TEAM_AWAY_R_4_DRAW_IN_ROW("Гости на выезде - 4 ничьи подряд"),
//    WDL_AWAY_TEAM_AWAY_R_5_DRAW_IN_ROW("Гости на выезде - 5 ничьи подряд"),
//    WDL_AWAY_R_TEAM_0_LOSE("Гости - 0 поражений в 5 матчах"),
//    WDL_AWAY_R_TEAM_1_LOSE("Гости - 1 поражение в 5 матчах"),
//    WDL_AWAY_R_TEAM_2_LOSE("Гости - 2 поражений в 5 матчах"),
//    WDL_AWAY_R_TEAM_3_LOSE("Гости - 3 поражений в 5 матчах"),
//    WDL_AWAY_R_TEAM_4_LOSE("Гости - 4 поражений в 5 матчах"),
//    WDL_AWAY_R_TEAM_2_LOSE_IN_ROW("Гости - 2 поражений подряд"),
//    WDL_AWAY_R_TEAM_3_LOSE_IN_ROW("Гости - 3 поражений подряд"),
//    WDL_AWAY_R_TEAM_4_LOSE_IN_ROW("Гости - 4 поражений подряд"),
//    WDL_AWAY_R_TEAM_5_LOSE_IN_ROW("Гости - 5 поражений подряд"),
//    WDL_AWAY_TEAM_AWAY_R_0_LOSE("Гости на выезде - 0 поражений в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_1_LOSE("Гости на выезде - 1 поражение в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_2_LOSE("Гости на выезде - 2 поражений в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_3_LOSE("Гости на выезде - 3 поражений в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_4_LOSE("Гости на выезде - 4 поражений в 5 матчах"),
//    WDL_AWAY_TEAM_AWAY_R_2_LOSE_IN_ROW("Гости на выезде - 2 поражений подряд"),
//    WDL_AWAY_TEAM_AWAY_R_3_LOSE_IN_ROW("Гости на выезде - 3 поражений подряд"),
//    WDL_AWAY_TEAM_AWAY_R_4_LOSE_IN_ROW("Гости на выезде - 4 поражений подряд"),
//    WDL_AWAY_TEAM_AWAY_R_5_LOSE_IN_ROW("Гости на выезде - 5 поражений подряд"),
//
//    /**
//     * Личные встречи
//     */
//    H2H_R_1X_SUPERIORITY("Явный перевес хозяев на результат 1Х"),
//    H2H_R_HOME_SUPERIORITY("Явный перевес побед хозяев в личных встречах"),
//    H2H_R_HOME_2_WIN_IN_ROW("Личные встречи - 2 победы хозяев подряд");


    private Integer groupId;
    private String description;


    Criteria(Integer groupId, String description) {
        this.groupId = groupId;
        this.description = description;
    }

    public static String getJson(Integer groupId) {
        StringBuilder json = new StringBuilder();
        String template = "{ opt: '%s', text: '%s'},";

        Stream.of(values()).filter(value -> value.getGroupId().equals(groupId))
                .forEach(value -> json.append(String.format(template, value.name(), value.getDescription())));
        return json.toString();
    }

}
